version: '3'
services:
  mosquitto:
    build: .
    image: eclipse-mosquitto
    container_name: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
  node:
    build:
      context: '.'
      dockerfile: NodeDockerfile
    container_name: node-ampq
    restart: always
    ports:
      - 3000:3000